//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenterMotivationCalc.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ИЦ")]
        public string EmployeesListSheetName {
            get {
                return ((string)(this["EmployeesListSheetName"]));
            }
            set {
                this["EmployeesListSheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int EmployeesListFirstRow {
            get {
                return ((int)(this["EmployeesListFirstRow"]));
            }
            set {
                this["EmployeesListFirstRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string EmployeesListShortnameColumn {
            get {
                return ((string)(this["EmployeesListShortnameColumn"]));
            }
            set {
                this["EmployeesListShortnameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public string EmployeesListFullnameColumn {
            get {
                return ((string)(this["EmployeesListFullnameColumn"]));
            }
            set {
                this["EmployeesListFullnameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string EmployeesListPositionColumn {
            get {
                return ((string)(this["EmployeesListPositionColumn"]));
            }
            set {
                this["EmployeesListPositionColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public string EmployeesListSalaryColumn {
            get {
                return ((string)(this["EmployeesListSalaryColumn"]));
            }
            set {
                this["EmployeesListSalaryColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public string EmployeesListRateColumn {
            get {
                return ((string)(this["EmployeesListRateColumn"]));
            }
            set {
                this["EmployeesListRateColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public string EmployeesListPfrColumn {
            get {
                return ((string)(this["EmployeesListPfrColumn"]));
            }
            set {
                this["EmployeesListPfrColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Лист1")]
        public string TimetablePlanSheetName {
            get {
                return ((string)(this["TimetablePlanSheetName"]));
            }
            set {
                this["TimetablePlanSheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int TimetablePlanFirstRow {
            get {
                return ((int)(this["TimetablePlanFirstRow"]));
            }
            set {
                this["TimetablePlanFirstRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string TimetablePlanShortNameColumn {
            get {
                return ((string)(this["TimetablePlanShortNameColumn"]));
            }
            set {
                this["TimetablePlanShortNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AI")]
        public string TimetablePlanTotalHoursColumn {
            get {
                return ((string)(this["TimetablePlanTotalHoursColumn"]));
            }
            set {
                this["TimetablePlanTotalHoursColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("стр1")]
        public string TimetableFactSheetName {
            get {
                return ((string)(this["TimetableFactSheetName"]));
            }
            set {
                this["TimetableFactSheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int TimetableFactFirstRow {
            get {
                return ((int)(this["TimetableFactFirstRow"]));
            }
            set {
                this["TimetableFactFirstRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public string TimetableFactShortNameColumn {
            get {
                return ((string)(this["TimetableFactShortNameColumn"]));
            }
            set {
                this["TimetableFactShortNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U")]
        public string TimetableFactTotalHoursColumn {
            get {
                return ((string)(this["TimetableFactTotalHoursColumn"]));
            }
            set {
                this["TimetableFactTotalHoursColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public string TimetableFactFirstDayColumn {
            get {
                return ((string)(this["TimetableFactFirstDayColumn"]));
            }
            set {
                this["TimetableFactFirstDayColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string TimetableFactLastDayColumn {
            get {
                return ((string)(this["TimetableFactLastDayColumn"]));
            }
            set {
                this["TimetableFactLastDayColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V")]
        public string TimetableFactNightHoursColumn {
            get {
                return ((string)(this["TimetableFactNightHoursColumn"]));
            }
            set {
                this["TimetableFactNightHoursColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("сотрудники")]
        public string OperatorsQualitySheetName {
            get {
                return ((string)(this["OperatorsQualitySheetName"]));
            }
            set {
                this["OperatorsQualitySheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int OperatorsQualityFirstRow {
            get {
                return ((int)(this["OperatorsQualityFirstRow"]));
            }
            set {
                this["OperatorsQualityFirstRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string OperatorsQualityFullNameColumn {
            get {
                return ((string)(this["OperatorsQualityFullNameColumn"]));
            }
            set {
                this["OperatorsQualityFullNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I")]
        public string OperatorsQualityAverageScoreColumn {
            get {
                return ((string)(this["OperatorsQualityAverageScoreColumn"]));
            }
            set {
                this["OperatorsQualityAverageScoreColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public float OperatorsQualityStandardValue {
            get {
                return ((float)(this["OperatorsQualityStandardValue"]));
            }
            set {
                this["OperatorsQualityStandardValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public float OperatorsQualityDesiredValue {
            get {
                return ((float)(this["OperatorsQualityDesiredValue"]));
            }
            set {
                this["OperatorsQualityDesiredValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public float OperatorsQualityMaxCoefficient {
            get {
                return ((float)(this["OperatorsQualityMaxCoefficient"]));
            }
            set {
                this["OperatorsQualityMaxCoefficient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("исходные")]
        public string OperatorsWorktimeSheetName {
            get {
                return ((string)(this["OperatorsWorktimeSheetName"]));
            }
            set {
                this["OperatorsWorktimeSheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int OperatorsWorktimeFirstRow {
            get {
                return ((int)(this["OperatorsWorktimeFirstRow"]));
            }
            set {
                this["OperatorsWorktimeFirstRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string OperatorsWorktimeFullNameColumn {
            get {
                return ((string)(this["OperatorsWorktimeFullNameColumn"]));
            }
            set {
                this["OperatorsWorktimeFullNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public string OperatorsWorktimeTotalCallsTimeColumn {
            get {
                return ((string)(this["OperatorsWorktimeTotalCallsTimeColumn"]));
            }
            set {
                this["OperatorsWorktimeTotalCallsTimeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string OperatorsWorktimeRemainingTimeColumn {
            get {
                return ((string)(this["OperatorsWorktimeRemainingTimeColumn"]));
            }
            set {
                this["OperatorsWorktimeRemainingTimeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X")]
        public string OperatorsWorktimePauseTimeColumn {
            get {
                return ((string)(this["OperatorsWorktimePauseTimeColumn"]));
            }
            set {
                this["OperatorsWorktimePauseTimeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.35")]
        public float OperatorsWorktimeStandardValue {
            get {
                return ((float)(this["OperatorsWorktimeStandardValue"]));
            }
            set {
                this["OperatorsWorktimeStandardValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.45")]
        public float OperatorsWorktimeDesiredValue {
            get {
                return ((float)(this["OperatorsWorktimeDesiredValue"]));
            }
            set {
                this["OperatorsWorktimeDesiredValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public float OperatorsWorktimeMaxCoefficient {
            get {
                return ((float)(this["OperatorsWorktimeMaxCoefficient"]));
            }
            set {
                this["OperatorsWorktimeMaxCoefficient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("statistics")]
        public string AcceptedAndMissedCallsSheetName {
            get {
                return ((string)(this["AcceptedAndMissedCallsSheetName"]));
            }
            set {
                this["AcceptedAndMissedCallsSheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int AcceptedAndMissedCallsFirstRow {
            get {
                return ((int)(this["AcceptedAndMissedCallsFirstRow"]));
            }
            set {
                this["AcceptedAndMissedCallsFirstRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string AcceptedAndMissedCallsDateTimeColumn {
            get {
                return ((string)(this["AcceptedAndMissedCallsDateTimeColumn"]));
            }
            set {
                this["AcceptedAndMissedCallsDateTimeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public string AcceptedAndMissedCallsTotalCallsColumn {
            get {
                return ((string)(this["AcceptedAndMissedCallsTotalCallsColumn"]));
            }
            set {
                this["AcceptedAndMissedCallsTotalCallsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X")]
        public string AcceptedAndMissedCallsMissedCallsColumn {
            get {
                return ((string)(this["AcceptedAndMissedCallsMissedCallsColumn"]));
            }
            set {
                this["AcceptedAndMissedCallsMissedCallsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z")]
        public string AcceptedAndMissedCallsWrongCallsColumn {
            get {
                return ((string)(this["AcceptedAndMissedCallsWrongCallsColumn"]));
            }
            set {
                this["AcceptedAndMissedCallsWrongCallsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public float AcceptedAndMissedCallsStandardValue {
            get {
                return ((float)(this["AcceptedAndMissedCallsStandardValue"]));
            }
            set {
                this["AcceptedAndMissedCallsStandardValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float AcceptedAndMissedCallsDesiredValue {
            get {
                return ((float)(this["AcceptedAndMissedCallsDesiredValue"]));
            }
            set {
                this["AcceptedAndMissedCallsDesiredValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public float AcceptedAndMissedCallsMaxCoefficient {
            get {
                return ((float)(this["AcceptedAndMissedCallsMaxCoefficient"]));
            }
            set {
                this["AcceptedAndMissedCallsMaxCoefficient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int AcceptedAndMissedCallsMorningLastHour {
            get {
                return ((int)(this["AcceptedAndMissedCallsMorningLastHour"]));
            }
            set {
                this["AcceptedAndMissedCallsMorningLastHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int AcceptedAndMissedCallsNightFirstHour {
            get {
                return ((int)(this["AcceptedAndMissedCallsNightFirstHour"]));
            }
            set {
                this["AcceptedAndMissedCallsNightFirstHour"] = value;
            }
        }
    }
}
